export const Wording = {
  email_format_invalid: "Vérifiez que le format soit correct.",
  password_required: "Mot de passe obligatoire",
  previous: "Précédent",
  next: "Suivant",
  field_required: "Veuillez remplir le champ obligatoire",
  countryPhone_required: "Veuillez choisir un pays",
  countryPhone_empty: "entrer le numéro de téléphone",
  countryPhone_valide: "Veuillez entrer un numéro de téléphone valide",
  passwords_must_match: "Les mots de passe doivent être identiques",
  email_must_match: "Les adresses mail doivent être identiques",
  password_check:
    "Le mot de passe doit comporter au moins 8 caractères et inclure au moins un chiffre et un symbole.",
  password_max_min_limit:
    "Votre mot de passe doit contenir entre 6 et 10 caractères.",
  code_limit: "Votre mot de passe doit contenir entre 8 et 10 caractères.",
  email_exists: "Ce e-mail est déjà utilisé.",
  organization_not_found: "Le code fourni n'est pas valide.",
  P2002: "Le numéro de téléphone est déjà utilisé par un autre compte",
  forgetPasswordSuccessed:
    "Merci. si un compte existe avec cette adresse e-mail, vous  devriez recevoir un e-mail pour réinitialiser votre mot depasse. Sinon, veuillez contacter le support.",
  forgetPasswordFailed:
    "Désolé, aucun compte n'existe avec cette adresse e-mail. Veuillez vérifier votre e-mail ou contacter le support pour obtenir de l'aide.",
  success: "succès",
  danger: "échec",
  error: "Requête ou service inaccessible. Réessayez plus tard",
  agendaNotfound: "L'agenda demandé n'est pas disponible.",
  notfoudnDESC: "Veuillez mettre à jour votre recherche ou vos filtres",
  descriptionAgenda: "Description de l'agenda",
  organizerWord: "Mot de l’organisateur",
  days: "Jours",
  hours: "Heures",
  minutues: "Minutes",
  seconds: "Secondes",
  eventParticipate: "Participez à l'événement",
  when: "Quand",
  where: "Où",
  duration: "Durée",
  org_description: "Description de l'institut",
  institutionNotFound: "L'institution demandé n'est pas disponible.",
};
